version: "3.9"

services:
  vault:
    image: hashicorp/vault:1.13.3
    container_name: vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    env_file:
      - .env
    volumes:
      - ./config.hcl:/vault/config/config.hcl
    command: server -config=/vault/config/config.hcl
