# services:
#   vault:
#     image: vault:1.13.3
#     container_name: vault
#     environment:
#       - VAULT_DEV_ROOT_TOKEN_ID=myroot
#       - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
#     ports:
#       - "8200:8200"
#     cap_drop:
#       - ALL  # 🔹 elimina las capacidades que Render no permite

services:
  vault:
    image: vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    env_file:
      - .env
    volumes:
      - ./vault-config.hcl:/vault/config/vault-config.hcl
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
